
import React from 'react';

interface HelpModalProps {
  isOpen: boolean;
  onClose: () => void;
}

// FIX: Implement the HelpModal component.
export const HelpModal: React.FC<HelpModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) {
    return null;
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex justify-center items-center" aria-modal="true" role="dialog">
      <div className="bg-white rounded-lg shadow-xl max-w-lg w-full m-4">
        <div className="p-6 border-b border-slate-200 flex justify-between items-center">
          <h2 className="text-xl font-semibold text-slate-800">About This App</h2>
          <button
            onClick={onClose}
            className="p-1 rounded-full text-slate-400 hover:bg-slate-100 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-label="Close modal"
          >
            <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd"></path>
            </svg>
          </button>
        </div>
        <div className="p-6 space-y-4 text-slate-600">
          <p>
            This application uses Google's Gemini model to classify Iris flower species based on their sepal and petal measurements.
          </p>
          <p>
            The images for each species are also generated by an Imagen model via the Gemini API, showcasing its multi-modal capabilities.
          </p>
          <div>
            <h3 className="font-semibold text-slate-700 mb-1">How to Use:</h3>
            <ol className="list-decimal list-inside space-y-1">
              <li>Enter the sepal length, sepal width, petal length, and petal width in centimeters.</li>
              <li>You can use the example buttons to pre-fill the form with typical measurements for each species.</li>
              <li>Click the "Classify Flower" button to submit the data to the AI model.</li>
              <li>The predicted species will be displayed in the result area below the form.</li>
            </ol>
          </div>
          <p>
            This is a demonstration of how generative AI can be applied to classic machine learning problems like classification.
          </p>
        </div>
        <div className="p-4 bg-slate-50 border-t border-slate-200 text-right">
            <button
                onClick={onClose}
                className="bg-indigo-600 text-white font-bold py-2 px-4 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors"
            >
                Got it!
            </button>
        </div>
      </div>
    </div>
  );
};
